### ISSUE TITLE
Refreshing can cause the Options button to be selected, but with Buy/Sell visible.

### ISSUE THREAD

**Issue by feralinprog** [Jashaszun/stonks#9]
If the trades form has Options selected and then I refresh, the form still has Options selected but the allowed actions are Buy/Sell instead of BTO/STC/STO/BTC.

**Comment by Jashaszun** [comment]
What browser are you using? I don't see this issue on Firefox.

**Comment by feralinprog** [comment]
Firefox.

**Comment by feralinprog** [comment]
Hmm, just tried again and cannot reproduce the issue. When I refresh the page now, the trades form is reset, with "Shares" and "Buy" selected.
